import { GetInputConfigType } from '@/types'

export const getInputPieceConfig: GetInputConfigType[][] = [
  [
    {
      id: '0',
      label: 'Nom',
      name: 'fr',
      placeholder: 'Entrez le nom de l Oeuvre',
      required: true,
      section: 'name',
      sectionLabel: 'Nom de l Oeuvre',
      translate: true,
      type: 'text',
    },
    {
      id: '100',
      label: 'Name (English)',
      language: 'en',
      name: 'en',
      placeholder: 'Entrez le nom de l Oeuvre (English)',
      required: true,
      rightSideVisible: true,
      section: 'name',
      sectionLabel: 'Nom de l Oeuvre',
      type: 'text',
    },
  ],
  [
    {
      accessType: 'image/*',
      fileType: 'image',
      id: '14',
      label: 'Image de l Oeuvre',
      name: 'image',
      placeholder: 'Telecharger l image de l Oeuvre',
      required: false,
      section: 'content',
      sectionLabel: 'Image de l Oeuvre',
      type: 'file',
    },
  ],
  [
    {
      id: '11',
      label: 'Description Standard',
      language: 'fr',
      mode: 'standard',
      name: 'description',
      placeholder: 'Entrez la description de l Oeuvre',
      required: false,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton standard',
      translate: true,
      type: 'text',
    },
    {
      id: '110',
      label: 'Description Standard (ENGLISH)',
      language: 'en',
      mode: 'standard',
      name: 'descritpion',
      placeholder: 'Entrez la description de l Oeuvre en Anglais',
      required: false,
      rightSideVisible: true,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton standard',
      type: 'text',
    },
  ],
  [
    {
      id: '12',
      label: 'Description FALC ou Facile à lire',
      language: 'fr',
      mode: 'falc',
      name: 'falc',
      placeholder: 'Entrez la description facile a lire de l Oeuvre',
      required: false,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton FALC',
      translate: true,
      type: 'text',
    },
    {
      id: '120',
      label: 'Description FALC ou Facile à lire (ENGLISH)',
      language: 'en',
      mode: 'falc',
      name: 'descritpion',
      placeholder: 'Entrez la description FALC de l Oeuvre en anglais',
      required: false,
      rightSideVisible: true,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton standard',
      type: 'text',
    },
  ],
  [
    {
      accessType: 'audio/*',
      fileType: 'audio',
      id: '13',
      label: 'Audio standard',
      language: 'fr',
      name: 'standard',
      placeholder: 'Telecharger l audio de l Oeuvre',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio standard',
      type: 'file',
    },
    {
      accessType: 'audio/*',
      fileType: 'audio',
      id: '130',
      label: 'Audio standard (English)',
      language: 'en',
      name: 'standard',
      placeholder: 'Telecharger l audio de l Oeuvre',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio standard',
      type: 'file',
    },
  ],
  [
    {
      accessType: 'audio/*',
      fileType: 'audio',
      id: '15',
      label: 'Audio FALC ou Facile a lire et à comprendre',
      language: 'fr',
      name: 'falc',
      placeholder: 'Telecharger l audio FALC de l Oeuvre',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio FALC',
      type: 'file',
    },
    {
      accessType: 'audio/*',
      fileType: 'audio',
      id: '150',
      label: 'Audio FALC ou Facile a lire (English)',
      language: 'en',
      name: 'falc',
      placeholder: 'Telecharger l audio FALC traduit de l Oeuvre',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio FALC',
      type: 'file',
    },
  ],
]
