import { GetInputConfigType } from '@/types'

export const getInputPlaceConfig: GetInputConfigType[][] = [
  [
    {
      id: '0',
      label: 'Nom',
      name: 'name',
      placeholder: 'Entrez le nom du lieu',
      required: true,
      section: 'name',
      sectionLabel: 'Information du Lieu',
      translate: true,
    },
  ],
  [
    {
      accessType: 'image/*',
      id: '14',
      label: 'Image',
      name: 'image',
      placeholder: 'Telecharger l image du lieu',
      required: false,
      section: 'image',
      sectionLabel: 'Image du lieu',
      type: 'file',
    },
  ],
  [
    {
      id: '3',
      label: 'Adresse',
      name: 'address',
      placeholder: 'Entrez le nom de la rue',
      required: false,
      section: 'address',
      sectionLabel: 'Information client',
      translate: false,
      type: 'text',
    },
    {
      id: '4',
      label: 'Ville',
      name: 'city',
      placeholder: 'Entrez la ville',
      required: false,
      section: 'address',
      sectionLabel: 'Information client',
      translate: false,
      type: 'text',
    },
    {
      id: '5',
      label: 'Pays',
      name: 'country',
      placeholder: 'Entrez le pays',
      required: false,
      section: 'address',
      sectionLabel: 'Information client',
      translate: false,
      type: 'text',
    },
    {
      id: '6',
      label: 'Code postal',
      name: 'postal',
      placeholder: 'Entrez le code postal',
      required: false,
      section: 'address',
      sectionLabel: 'Information client',
      translate: false,
      type: 'number',
    },
  ],
  [
    {
      id: '7',
      label: 'Latitude',
      name: 'lat',
      placeholder: 'Entrez la latitude',
      required: false,
      section: 'coords',
      sectionLabel: 'Coordonnées géographique',
      translate: true,
      type: 'number',
    },
    {
      id: '8',
      label: 'Longitude',
      name: 'lon',
      placeholder: 'Entrez la longitude',
      required: false,
      section: 'coords',
      sectionLabel: 'Coordonnées géographique',
      translate: true,
      type: 'number',
    },
    {
      id: '10',
      label: 'Localisation utilisateur obligatiore',
      locationRequired: false,
      name: 'locationRequired',
      placeholder: 'Cochez',
      required: false,
      rows: 10,
      section: 'coords',
      sectionLabel: 'Descripton standard',
      translate: true,
      type: 'checkbox',
    },
  ],
  [
    {
      id: '11',
      label: 'Description standard',
      language: 'fr',
      name: 'standard',
      placeholder: 'Entrez la description du lieu',
      required: false,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton standard',
      translate: true,
      type: 'text',
    },
  ],
  [
    {
      id: '12',
      label: 'Description FALC ou Facile à lire',
      language: 'fr',
      name: 'falc',
      placeholder: 'Entrez la description facile a lire du lieu',
      required: false,
      rows: 10,
      section: 'description',
      sectionLabel: 'Descripton FALC ou Facile a lire',
      translate: true,
      type: 'text',
    },
  ],
  [
    {
      accessType: 'audio/*',
      id: '12',
      label: 'Audio standard',
      language: 'fr',
      name: 'standard',
      placeholder: 'Telecharger l audio du lieu',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio standard',
      type: 'file',
    },
    {
      accessType: 'audio/*',
      id: '13',
      label: 'Audio Facile a comprendre',
      language: 'fr',
      name: 'falc',
      placeholder: 'Telecharger l audio du lieu',
      required: false,
      section: 'audio',
      sectionLabel: 'Audio standard',
      type: 'file',
    },
  ],
  [],
]
