import { GetInputConfigType } from '@/types'

export const getInputPlaceConfig: GetInputConfigType[][] = [
  [
    {
      id: '011',
      label: 'Type de lieu',
      name: 'type',
      option: ['MUSEUM', 'CASTLE', 'OUTDOOR'],
      placeholder: 'Selectionnez le type',
      required: true,
      section: 'content',
      sectionLabel: 'Type de Lieu',
      translate: false,
    },
    {
      id: '0',
      label: 'Nom',
      name: 'fr',
      placeholder: 'Entrez le nom du lieu',
      required: true,
      section: 'name',
      sectionLabel: 'Nom du Lieu',
      translate: true,
      type: 'text',
    },
    {
      id: '100',
      label: 'Name (English)',
      language: 'en',
      name: 'en',
      placeholder: 'Entrez le nom du lieu en Anglais',
      required: true,
      rightSideVisible: true,
      section: 'name',
      sectionLabel: 'Nom du lieu',
      type: 'text',
    },
  ],
  [
    {
      accessType: 'image/*',
      fileType: 'image',
      id: '14',
      label: 'Image du lieu',
      name: 'image',
      placeholder: 'Telecharger l image du lieu',
      required: false,
      section: 'content',
      sectionLabel: 'Image du lieu',
      type: 'file',
    },
  ],
  [
    {
      id: '3',
      label: 'Adresse',
      name: 'address',
      placeholder: 'Entrez le nom de la rue',
      required: false,
      section: 'address',
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '4',
      label: 'Ville',
      name: 'city',
      placeholder: 'Entrez la ville',
      required: false,
      section: 'address',
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '5',
      label: 'Pays',
      name: 'country',
      placeholder: 'Entrez le pays',
      required: false,
      section: 'address',
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '6',
      label: 'Code postal',
      name: 'postal',
      placeholder: 'Entrez le code postal',
      required: false,
      section: 'address',
      sectionLabel: 'Adresse',
      translate: false,
      type: 'number',
    },
  ],
  [
    {
      id: '7',
      label: 'Latitude',
      name: 'lat',
      placeholder: 'Entrez la latitude',
      required: false,
      section: 'coords',
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'number',
    },
    {
      id: '8',
      label: 'Longitude',
      name: 'lon',
      placeholder: 'Entrez la longitude',
      required: false,
      section: 'coords',
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'number',
    },
    {
      id: '10',
      isLocationRequired: false,
      label: 'Localisation utilisateur obligatoire',
      name: 'locationRequired',
      placeholder: 'Cochez',
      required: false,
      section: 'coords',
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'checkbox',
    },
  ],
  [
    {
      id: '111',
      label: 'Validation des donées du Lieu',
      sectionLabel: 'VALIDATION',
      name: 'fr',
      placeholder: 'Entrez le nom du lieu',
      required: true,
      section: 'name',
      type: 'hidden',
    },
  ],
  //   [
  //     {
  //       id: '11',
  //       label: 'Description Standard',
  //       language: 'fr',
  //       mode: 'standard',
  //       name: 'description',
  //       placeholder: 'Entrez la description "standard" du Lieu en Francais',
  //       required: false,
  //       rightSideVisible: true,
  //       rows: 10,
  //       section: 'description',
  //       sectionLabel: 'Description Francais',
  //       translate: true,
  //       type: 'text',
  //     },
  //   ],
  //   [
  //     {
  //       id: '12',
  //       label: 'Description FALC ou Facile à lire',
  //       language: 'fr',
  //       mode: 'falc',
  //       name: 'descriptionFalc',
  //       placeholder: 'Entrez la description "FALC" du Lieu en Francais',
  //       rightSideVisible: true,
  //       required: false,
  //       rows: 10,
  //       section: 'description',
  //       sectionLabel: 'Descripton FALC Francais',
  //       translate: true,
  //       type: 'text',
  //     },
  //   ],
  //   [
  //     {
  //       id: '110',
  //       label: 'Description Standard (ENGLISH)',
  //       language: 'en',
  //       mode: 'standard',
  //       name: 'description',
  //       placeholder: 'Entrez la description "standard" du Lieu en Anglais',
  //       required: false,
  //       rightSideVisible: true,
  //       rows: 10,
  //       section: 'description',
  //       sectionLabel: 'Descripton Anglaise',
  //       type: 'text',
  //     },
  //   ],
  //   [
  //     {
  //       id: '120',
  //       label: 'Description FALC ou Facile à lire (ENGLISH)',
  //       language: 'en',
  //       mode: 'falc',
  //       name: 'descritpion',
  //       placeholder: 'Entrez la description "FALC" du Lieu en Anglais',
  //       required: false,
  //       rightSideVisible: true,
  //       rows: 10,
  //       section: 'description',
  //       sectionLabel: 'Descripton FALC Anglaise',
  //       type: 'text',
  //     },
  //   ],
]
