import { GetInputConfigType } from '@/types'

export const getInputJourneyConfig: GetInputConfigType[][] = [
  [
    {
      id: '011',
      label: 'Type de Parcours',
      name: 'type',
      option: ['museum', 'castle', 'outdoor'],
      placeholder: 'Selectionnez le type',
      required: true,
      sectionLabel: 'Type de Parcours',
      translate: false,
    },
    {
      id: '0112',
      label: 'Durée du Parcours (minutes)',
      name: 'duration',
      placeholder: 'Selectionnez le type',
      required: true,
      sectionLabel: 'Durée',
      translate: false,
      type: 'number',
    },
  ],
  [
    {
      id: '0',
      label: 'Nom du parcours',
      name: 'name',
      placeholder: 'Entrez le nom du parcours',
      required: true,
      sectionLabel: 'Nom du Parcours',
      translate: true,
      type: 'text',
    },
  ],
  [
    {
      id: '3',
      label: 'Adresse',
      name: 'address',
      placeholder: 'Entrez le nom de la rue',
      required: false,
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '4',
      label: 'Ville',
      name: 'city',
      placeholder: 'Entrez la ville',
      required: false,
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '5',
      label: 'Pays',
      name: 'country',
      placeholder: 'Entrez le pays',
      required: false,
      sectionLabel: 'Adresse',
      translate: false,
      type: 'text',
    },
    {
      id: '6',
      label: 'Code postal',
      name: 'postal',
      placeholder: 'Entrez le code postal',
      required: false,
      sectionLabel: 'Adresse',
      translate: false,
      type: 'number',
    },
  ],
  [
    {
      id: '7',
      label: 'Latitude',
      name: 'lat',
      placeholder: 'Entrez la latitude',
      required: false,
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'number',
    },
    {
      id: '8',
      label: 'Longitude',
      name: 'lon',
      placeholder: 'Entrez la longitude',
      required: false,
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'number',
    },
    {
      id: '10',
      isLocationRequired: false,
      label: 'Localisation utilisateur obligatoire',
      name: 'location_required',
      placeholder: 'Cochez',
      required: false,
      sectionLabel: 'Coordonnées géo.',
      translate: false,
      type: 'checkbox',
    },
  ],
  [
    {
      accessType: 'image/*',
      fileType: 'image',
      id: '14',
      label: 'Image du parcours',
      name: 'image',
      placeholder: 'Telecharger l image du parcours',
      required: false,
      sectionLabel: 'Image du parcours',
      type: 'file',
    },
  ],
]
